version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - '${IP}:8080:80'
    environment:
      TZ: Asia/Tokyo
    tty: true
    volumes:
      - ./src/frontend:/data
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data
    container_name: hg_web
    networks:
      hg_network:
        ipv4_address: 192.169.1.2

  hg_app:
    build:
      context: .
      dockerfile: ./Docker/node/Dockerfile
    container_name: hg_app
    environment:
      TZ: Asia/Tokyo
      NODE_OPTIONS: "--max-old-space-size=8192"
    volumes:
      - ./src/frontend:/home/node/app
      - yarn-cache:/home/node/.cache/yarn:rw
    ports:
      - '${IP}:3000:3000'
    tty: true
    networks:
      hg_network:
        ipv4_address: 192.169.1.3

  hg_api:
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    container_name: hg_api
    environment:
      TZ: Asia/Tokyo
      NODE_OPTIONS: "--max-old-space-size=8192"
    volumes:
      - ./src/api:/data
      - yarn-cache:/home/node/.cache/yarn:rw
    expose:
      - 9000
    tty: true
    networks:
      hg_network:
        ipv4_address: 192.169.1.4

  hg_db:
    build:
      context: .
      dockerfile: ./Docker/db/Dockerfile
    ports:
      - "${IP}:3306:3306"
    environment:
      MYSQL_DATABASE: hg_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - hg-db-store:/var/lib/mysql
    container_name: hg_db
    networks:
      hg_network:
        ipv4_address: 192.169.1.5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - hg_db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=hg_db
      - PMA_USER=user
      - PMA_PASSWORD=password
    platform: linux/amd64
    ports:
      - "${IP}:4400:80"
    networks:
      hg_network:
        ipv4_address: 192.169.1.6

  mail:
    image: mailhog/mailhog
    platform: linux/amd64
    container_name: hg_mailhog
    ports:
      - "${IP}:8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp
    networks:
      hg_network:
        ipv4_address: 192.169.1.7

volumes:
  yarn-cache:
  hg-db-store:
  maildir:

networks:
  hg_network:
    external: true